name: CI
on:
  merge_group:
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        java: [17, 25]
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-java@ad2b38190b15e4d6bdf0c97fb4fca8412226d287 # v5.3.0
      with:
        java-version: ${{matrix.java}}
        distribution: adopt
    - uses: sbt/setup-sbt@v1
    - run: sbt -v
           --server
           scalafmtSbtCheck
           scalafmtCheckAll
           test
           publishLocal
           scripted
    - run: rm -rf ~/.ivy2/local
