name: CI
on:
  merge_group:
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        java: [17, 25]
    steps:
    - uses: actions/checkout@v7
    - uses: actions/setup-java@03ad4de0992f5dab5e18fcb136590ce7c4a0ac95 # v5.6.0
      with:
        java-version: ${{matrix.java}}
        distribution: adopt
    - uses: sbt/setup-sbt@v1
    - run: sbt -v
           --server
           scalafmtSbtCheck
           scalafmtCheckAll
           test
           publishLocal
           scripted
    - run: rm -rf ~/.ivy2/local
