name: CI
on:
  merge_group:
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        java: [17, 25]
    steps:
    - uses: actions/checkout@v7
    - uses: actions/setup-java@1bcf9fb12cf4aa7d266a90ae39939e61372fe520 # v5.4.0
      with:
        java-version: ${{matrix.java}}
        distribution: adopt
    - uses: sbt/setup-sbt@v1
    - run: sbt -v
           --server
           scalafmtSbtCheck
           scalafmtCheckAll
           test
           publishLocal
           scripted
    - run: rm -rf ~/.ivy2/local
